## updatecli.yaml
name: Update Kernel Version
description: Update the Kernel version used in the build workflow to the latest stable release.

scms:
  github:
    kind: github
    spec:
      branch: {{ .github.branch }}
      email: {{ .github.email }}
      owner: {{ .github.owner }}
      repository: {{ .github.repository }}
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
      user: {{ .github.user }}
      username: {{ .github.username }}

actions:
  pr:
    kind: github/pullrequest
    scmid: github
    spec:
      title: "Update Kernel Version"
      # automerge: true
      draft: false
      labels:
        - "dependencies"
        - "kernel"

sources:
  kernelVersion:
    name: Get the latest Kernel version
    kind: shell
    spec:
      command: |
        curl -s https://cdn.kernel.org/pub/linux/kernel/v6.x/ | grep href | grep linux | grep tar.gz | awk -F'"' '{ print $2 }' | sed 's/linux-//' | sed 's/.tar.gz//' | sort --version-sort | tail -n 1

targets:
  bumpKernelVersion:
    name: Update pipeline to the latest Kernel version
    kind: file
    scmid: github
    spec:
      file: kernel
      content: '{{ source "kernelVersion" }}'
