## update-kernel-6x.yaml
name: Update Kernel 6.x Version
description: Update the 6.x kernel version used in the build workflow to the latest stable 6.x release.

scms:
  github:
    kind: github
    spec:
      branch: {{ .github.branch }}
      email: {{ .github.email }}
      owner: {{ .github.owner }}
      repository: {{ .github.repository }}
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
      user: {{ .github.user }}
      username: {{ .github.username }}

actions:
  pr:
    kind: github/pullrequest
    scmid: github
    spec:
      title: "Update Kernel 6.x Version"
      # automerge: true
      draft: false
      labels:
        - "dependencies"
        - "kernel"
        - "kernel-6x"

sources:
  kernelVersion:
    name: Get the latest Kernel 6.x version
    kind: shell
    spec:
      command: |
        curl -s https://cdn.kernel.org/pub/linux/kernel/v6.x/ | grep href | grep linux | grep tar.gz | awk -F'"' '{ print $2 }' | sed 's/linux-//' | sed 's/.tar.gz//' | sort --version-sort | tail -n 1

targets:
  bumpKernelVersion:
    name: Update pipeline to the latest Kernel 6.x version
    kind: file
    scmid: github
    spec:
      file: kernel-6x
      content: '{{ source "kernelVersion" }}'
